"""add_incident_tickets

Revision ID: 7d208bf8a385
Revises: d3ab65fe2191
Create Date: 2026-01-15 02:32:49.732033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d208bf8a385'
down_revision: Union[str, Sequence[str], None] = 'd3ab65fe2191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='ticketseverity'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', name='ticketstatus'), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_tickets')
    # ### end Alembic commands ###
